/**
 * Created on: 2015Äê4ÔÂ21ÈÕ
 */
package cn.ac.ioa.hccl.atm.vehicle;
import java.io.*;

/**
 * Vehicle detection zone sensitivity for raw responses.
 * @author nay0648
 */
public interface ZoneSensitivity extends Serializable
{
	/**
	 * get zone sensitivity
	 * @return
	 */
	public double sensitivity();
	
	/**
	 * to see if the zone should be activated by a certain response
	 * @param response
	 * the raw energy response generated by a detection zone
	 * @return
	 */
	public boolean isActive(double response);
}
